export const CURRENCIES = [
  {
    value: 'USD',
    name: 'US Dollar',
    label: 'US Dollar (USD $)',
    symbol: '$',
  },
  {
    value: 'EUR',
    name: 'Euro',
    label: 'Euro (EUR €)',
    symbol: '€',
  },
  {
    value: 'GBP',
    name: 'British Pound',
    label: 'British Pound (GBP £)',
    symbol: '£',
  },
  {
    value: 'CAD',
    name: 'Canadian Dollar',
    label: 'Canadian Dollar (CAD $)',
    symbol: '$',
  },
  {
    value: 'AFN',
    name: 'Afghan Afghani',
    label: 'Afghan Afghani (AFN ؋)',
    symbol: '؋',
  },
  {
    value: 'ALL',
    name: 'Albanian Lek',
    label: 'Albanian Lek (ALL)',
    symbol: 'ALL',
  },
  {
    value: 'DZD',
    name: 'Algerian Dinar',
    label: 'Algerian Dinar (DZD)',
    symbol: 'DZD',
  },
  {
    value: 'AOA',
    name: 'Angolan Kwanza',
    label: 'Angolan Kwanza (AOA Kz)',
    symbol: 'Kz',
  },
  {
    value: 'ARS',
    name: 'Argentine Peso',
    label: 'Argentine Peso (ARS $)',
    symbol: '$',
  },
  {
    value: 'AMD',
    name: 'Armenian Dram',
    label: 'Armenian Dram (AMD ֏)',
    symbol: '֏',
  },
  {
    value: 'AWG',
    name: 'Aruban Florin',
    label: 'Aruban Florin (AWG)',
    symbol: 'AWG',
  },
  {
    value: 'AUD',
    name: 'Australian Dollar',
    label: 'Australian Dollar (AUD $)',
    symbol: '$',
  },
  {
    value: 'BBD',
    name: 'Barbadian Dollar',
    label: 'Barbadian Dollar (BBD $)',
    symbol: '$',
  },
  {
    value: 'AZN',
    name: 'Azerbaijani Manat',
    label: 'Azerbaijani Manat (AZN ₼)',
    symbol: '₼',
  },
  {
    value: 'BDT',
    name: 'Bangladeshi Taka',
    label: 'Bangladeshi Taka (BDT ৳)',
    symbol: '৳',
  },
  {
    value: 'BSD',
    name: 'Bahamian Dollar',
    label: 'Bahamian Dollar (BSD $)',
    symbol: '$',
  },
  {
    value: 'BHD',
    name: 'Bahraini Dinar',
    label: 'Bahraini Dinar (BHD)',
    symbol: 'BHD',
  },
  {
    value: 'BIF',
    name: 'Burundian Franc',
    label: 'Burundian Franc (BIF)',
    symbol: 'BIF',
  },
  {
    value: 'BYN',
    name: 'Belarusian Ruble',
    label: 'Belarusian Ruble (BYN)',
    symbol: 'BYN',
  },
  {
    value: 'BZD',
    name: 'Belize Dollar',
    label: 'Belize Dollar (BZD $)',
    symbol: '$',
  },
  {
    value: 'BMD',
    name: 'Bermudan Dollar',
    label: 'Bermudan Dollar (BMD $)',
    symbol: '$',
  },
  {
    value: 'BTN',
    name: 'Bhutanese Ngultrum',
    label: 'Bhutanese Ngultrum (BTN)',
    symbol: 'BTN',
  },
  {
    value: 'BAM',
    name: 'Bosnia-Herzegovina Convertible Mark',
    label: 'Bosnia-Herzegovina Convertible Mark (BAM KM)',
    symbol: 'KM',
  },
  {
    value: 'BRL',
    name: 'Brazilian Real',
    label: 'Brazilian Real (BRL R$)',
    symbol: 'R$',
  },
  {
    value: 'BOB',
    name: 'Bolivian Boliviano',
    label: 'Bolivian Boliviano (BOB Bs)',
    symbol: 'Bs',
  },
  {
    value: 'BWP',
    name: 'Botswanan Pula',
    label: 'Botswanan Pula (BWP P)',
    symbol: 'P',
  },
  {
    value: 'BND',
    name: 'Brunei Dollar',
    label: 'Brunei Dollar (BND $)',
    symbol: '$',
  },
  {
    value: 'BGN',
    name: 'Bulgarian Lev',
    label: 'Bulgarian Lev (BGN)',
    symbol: 'BGN',
  },
  {
    value: 'MMK',
    name: 'Myanmar Kyat',
    label: 'Myanmar Kyat (MMK K)',
    symbol: 'K',
  },
  {
    value: 'KHR',
    name: 'Cambodian Riel',
    label: 'Cambodian Riel (KHR ៛)',
    symbol: '៛',
  },
  {
    value: 'CVE',
    name: 'Cape Verdean Escudo',
    label: 'Cape Verdean Escudo (CVE)',
    symbol: 'CVE',
  },
  {
    value: 'KYD',
    name: 'Cayman Islands Dollar',
    label: 'Cayman Islands Dollar (KYD $)',
    symbol: '$',
  },
  {
    value: 'XAF',
    name: 'Central African CFA Franc',
    label: 'Central African CFA Franc (XAF FCFA)',
    symbol: 'FCFA',
  },
  {
    value: 'CLP',
    name: 'Chilean Peso',
    label: 'Chilean Peso (CLP $)',
    symbol: '$',
  },
  {
    value: 'CNY',
    name: 'Chinese Yuan',
    label: 'Chinese Yuan (CNY ¥)',
    symbol: '¥',
  },
  {
    value: 'COP',
    name: 'Colombian Peso',
    label: 'Colombian Peso (COP $)',
    symbol: '$',
  },
  {
    value: 'KMF',
    name: 'Comorian Franc',
    label: 'Comorian Franc (KMF CF)',
    symbol: 'CF',
  },
  {
    value: 'CDF',
    name: 'Congolese Franc',
    label: 'Congolese Franc (CDF)',
    symbol: 'CDF',
  },
  {
    value: 'CRC',
    name: 'Costa Rican Colón',
    label: 'Costa Rican Colón (CRC ₡)',
    symbol: '₡',
  },
  {
    value: 'HRK',
    name: 'Croatian Kuna',
    label: 'Croatian Kuna (HRK kn)',
    symbol: 'kn',
  },
  {
    value: 'CZK',
    name: 'Czech Koruna',
    label: 'Czech Koruna (CZK Kč)',
    symbol: 'Kč',
  },
  {
    value: 'DKK',
    name: 'Danish Krone',
    label: 'Danish Krone (DKK kr)',
    symbol: 'kr',
  },
  {
    value: 'DJF',
    name: 'Djiboutian Franc',
    label: 'Djiboutian Franc (DJF)',
    symbol: 'DJF',
  },
  {
    value: 'DOP',
    name: 'Dominican Peso',
    label: 'Dominican Peso (DOP $)',
    symbol: '$',
  },
  {
    value: 'XCD',
    name: 'East Caribbean Dollar',
    label: 'East Caribbean Dollar (XCD $)',
    symbol: '$',
  },
  {
    value: 'EGP',
    name: 'Egyptian Pound',
    label: 'Egyptian Pound (EGP E£)',
    symbol: 'E£',
  },
  {
    value: 'ERN',
    name: 'Eritrean Nakfa',
    label: 'Eritrean Nakfa (ERN)',
    symbol: 'ERN',
  },
  {
    value: 'ETB',
    name: 'Ethiopian Birr',
    label: 'Ethiopian Birr (ETB)',
    symbol: 'ETB',
  },
  {
    value: 'FKP',
    name: 'Falkland Islands Pound',
    label: 'Falkland Islands Pound (FKP £)',
    symbol: '£',
  },
  {
    value: 'XPF',
    name: 'CFP Franc',
    label: 'CFP Franc (XPF CFPF)',
    symbol: 'CFPF',
  },
  {
    value: 'FJD',
    name: 'Fijian Dollar',
    label: 'Fijian Dollar (FJD $)',
    symbol: '$',
  },
  {
    value: 'GIP',
    name: 'Gibraltar Pound',
    label: 'Gibraltar Pound (GIP £)',
    symbol: '£',
  },
  {
    value: 'GMD',
    name: 'Gambian Dalasi',
    label: 'Gambian Dalasi (GMD)',
    symbol: 'GMD',
  },
  {
    value: 'GHS',
    name: 'Ghanaian Cedi',
    label: 'Ghanaian Cedi (GHS ₵)',
    symbol: '₵',
  },
  {
    value: 'GTQ',
    name: 'Guatemalan Quetzal',
    label: 'Guatemalan Quetzal (GTQ Q)',
    symbol: 'Q',
  },
  {
    value: 'GYD',
    name: 'Guyanaese Dollar',
    label: 'Guyanaese Dollar (GYD $)',
    symbol: '$',
  },
  {
    value: 'GEL',
    name: 'Georgian Lari',
    label: 'Georgian Lari (GEL ₾)',
    symbol: '₾',
  },
  {
    value: 'GNF',
    name: 'Guinean Franc',
    label: 'Guinean Franc (GNF FG)',
    symbol: 'FG',
  },
  {
    value: 'HTG',
    name: 'Haitian Gourde',
    label: 'Haitian Gourde (HTG)',
    symbol: 'HTG',
  },
  {
    value: 'HNL',
    name: 'Honduran Lempira',
    label: 'Honduran Lempira (HNL L)',
    symbol: 'L',
  },
  {
    value: 'HKD',
    name: 'Hong Kong Dollar',
    label: 'Hong Kong Dollar (HKD HK$)',
    symbol: 'HK$',
  },
  {
    value: 'HUF',
    name: 'Hungarian Forint',
    label: 'Hungarian Forint (HUF Ft)',
    symbol: 'Ft',
  },
  {
    value: 'ISK',
    name: 'Icelandic Króna',
    label: 'Icelandic Króna (ISK kr)',
    symbol: 'kr',
  },
  {
    value: 'INR',
    name: 'Indian Rupee',
    label: 'Indian Rupee (INR ₹)',
    symbol: '₹',
  },
  {
    value: 'IDR',
    name: 'Indonesian Rupiah',
    label: 'Indonesian Rupiah (IDR Rp)',
    symbol: 'Rp',
  },
  {
    value: 'ILS',
    name: 'Israeli New Shekel',
    label: 'Israeli New Shekel (ILS ₪)',
    symbol: '₪',
  },
  {
    value: 'IRR',
    name: 'Iranian Rial',
    label: 'Iranian Rial (IRR)',
    symbol: 'IRR',
  },
  {
    value: 'IQD',
    name: 'Iraqi Dinar',
    label: 'Iraqi Dinar (IQD)',
    symbol: 'IQD',
  },
  {
    value: 'JMD',
    name: 'Jamaican Dollar',
    label: 'Jamaican Dollar (JMD $)',
    symbol: '$',
  },
  {
    value: 'JPY',
    name: 'Japanese Yen',
    label: 'Japanese Yen (JPY ¥)',
    symbol: '¥',
  },
  {
    value: 'JEP',
    name: 'Jersey Pound',
    label: 'Jersey Pound (JEP)',
    symbol: 'JEP',
  },
  {
    value: 'JOD',
    name: 'Jordanian Dinar',
    label: 'Jordanian Dinar (JOD)',
    symbol: 'JOD',
  },
  {
    value: 'KZT',
    name: 'Kazakhstani Tenge',
    label: 'Kazakhstani Tenge (KZT ₸)',
    symbol: '₸',
  },
  {
    value: 'KES',
    name: 'Kenyan Shilling',
    label: 'Kenyan Shilling (KES)',
    symbol: 'KES',
  },
  {
    value: 'KID',
    name: 'Kiribati Dollar',
    label: 'Kiribati Dollar (KID)',
    symbol: 'KID',
  },
  {
    value: 'KWD',
    name: 'Kuwaiti Dinar',
    label: 'Kuwaiti Dinar (KWD)',
    symbol: 'KWD',
  },
  {
    value: 'KGS',
    name: 'Kyrgystani Som',
    label: 'Kyrgystani Som (KGS)',
    symbol: 'KGS',
  },
  {
    value: 'LAK',
    name: 'Laotian Kip',
    label: 'Laotian Kip (LAK ₭)',
    symbol: '₭',
  },
  {
    value: 'LVL',
    name: 'Latvian Lats',
    label: 'Latvian Lats (LVL)',
    symbol: 'LVL',
  },
  {
    value: 'LBP',
    name: 'Lebanese Pound',
    label: 'Lebanese Pound (LBP L£)',
    symbol: 'L£',
  },
  {
    value: 'LSL',
    name: 'Lesotho Loti',
    label: 'Lesotho Loti (LSL)',
    symbol: 'LSL',
  },
  {
    value: 'LRD',
    name: 'Liberian Dollar',
    label: 'Liberian Dollar (LRD $)',
    symbol: '$',
  },
  {
    value: 'LYD',
    name: 'Libyan Dinar',
    label: 'Libyan Dinar (LYD)',
    symbol: 'LYD',
  },
  {
    value: 'LTL',
    name: 'Lithuanian Litas',
    label: 'Lithuanian Litas (LTL)',
    symbol: 'LTL',
  },
  {
    value: 'MGA',
    name: 'Malagasy Ariary',
    label: 'Malagasy Ariary (MGA Ar)',
    symbol: 'Ar',
  },
  {
    value: 'MKD',
    name: 'Macedonian Denar',
    label: 'Macedonian Denar (MKD)',
    symbol: 'MKD',
  },
  {
    value: 'MOP',
    name: 'Macanese Pataca',
    label: 'Macanese Pataca (MOP)',
    symbol: 'MOP',
  },
  {
    value: 'MWK',
    name: 'Malawian Kwacha',
    label: 'Malawian Kwacha (MWK)',
    symbol: 'MWK',
  },
  {
    value: 'MVR',
    name: 'Maldivian Rufiyaa',
    label: 'Maldivian Rufiyaa (MVR)',
    symbol: 'MVR',
  },
  {
    value: 'MRU',
    name: 'Mauritanian Ouguiya',
    label: 'Mauritanian Ouguiya (MRU)',
    symbol: 'MRU',
  },
  {
    value: 'MXN',
    name: 'Mexican Peso',
    label: 'Mexican Peso (MXN $)',
    symbol: '$',
  },
  {
    value: 'MYR',
    name: 'Malaysian Ringgit',
    label: 'Malaysian Ringgit (MYR RM)',
    symbol: 'RM',
  },
  {
    value: 'MUR',
    name: 'Mauritian Rupee',
    label: 'Mauritian Rupee (MUR Rs)',
    symbol: 'Rs',
  },
  {
    value: 'MDL',
    name: 'Moldovan Leu',
    label: 'Moldovan Leu (MDL)',
    symbol: 'MDL',
  },
  {
    value: 'MAD',
    name: 'Moroccan Dirham',
    label: 'Moroccan Dirham (MAD)',
    symbol: 'MAD',
  },
  {
    value: 'MNT',
    name: 'Mongolian Tugrik',
    label: 'Mongolian Tugrik (MNT ₮)',
    symbol: '₮',
  },
  {
    value: 'MZN',
    name: 'Mozambican Metical',
    label: 'Mozambican Metical (MZN)',
    symbol: 'MZN',
  },
  {
    value: 'NAD',
    name: 'Namibian Dollar',
    label: 'Namibian Dollar (NAD $)',
    symbol: '$',
  },
  {
    value: 'NPR',
    name: 'Nepalese Rupee',
    label: 'Nepalese Rupee (NPR Rs)',
    symbol: 'Rs',
  },
  {
    value: 'ANG',
    name: 'Netherlands Antillean Guilder',
    label: 'Netherlands Antillean Guilder (ANG)',
    symbol: 'ANG',
  },
  {
    value: 'NZD',
    name: 'New Zealand Dollar',
    label: 'New Zealand Dollar (NZD $)',
    symbol: '$',
  },
  {
    value: 'NIO',
    name: 'Nicaraguan Córdoba',
    label: 'Nicaraguan Córdoba (NIO C$)',
    symbol: 'C$',
  },
  {
    value: 'NGN',
    name: 'Nigerian Naira',
    label: 'Nigerian Naira (NGN ₦)',
    symbol: '₦',
  },
  {
    value: 'NOK',
    name: 'Norwegian Krone',
    label: 'Norwegian Krone (NOK kr)',
    symbol: 'kr',
  },
  {
    value: 'OMR',
    name: 'Omani Rial',
    label: 'Omani Rial (OMR)',
    symbol: 'OMR',
  },
  {
    value: 'PAB',
    name: 'Panamanian Balboa',
    label: 'Panamanian Balboa (PAB)',
    symbol: 'PAB',
  },
  {
    value: 'PKR',
    name: 'Pakistani Rupee',
    label: 'Pakistani Rupee (PKR Rs)',
    symbol: 'Rs',
  },
  {
    value: 'PGK',
    name: 'Papua New Guinean Kina',
    label: 'Papua New Guinean Kina (PGK)',
    symbol: 'PGK',
  },
  {
    value: 'PYG',
    name: 'Paraguayan Guarani',
    label: 'Paraguayan Guarani (PYG ₲)',
    symbol: '₲',
  },
  {
    value: 'PEN',
    name: 'Peruvian Sol',
    label: 'Peruvian Sol (PEN)',
    symbol: 'PEN',
  },
  {
    value: 'PHP',
    name: 'Philippine Piso',
    label: 'Philippine Piso (PHP ₱)',
    symbol: '₱',
  },
  {
    value: 'PLN',
    name: 'Polish Zloty',
    label: 'Polish Zloty (PLN zł)',
    symbol: 'zł',
  },
  {
    value: 'QAR',
    name: 'Qatari Rial',
    label: 'Qatari Rial (QAR)',
    symbol: 'QAR',
  },
  {
    value: 'RON',
    name: 'Romanian Leu',
    label: 'Romanian Leu (RON lei)',
    symbol: 'lei',
  },
  {
    value: 'RUB',
    name: 'Russian Ruble',
    label: 'Russian Ruble (RUB ₽)',
    symbol: '₽',
  },
  {
    value: 'RWF',
    name: 'Rwandan Franc',
    label: 'Rwandan Franc (RWF RF)',
    symbol: 'RF',
  },
  {
    value: 'WST',
    name: 'Samoan Tala',
    label: 'Samoan Tala (WST)',
    symbol: 'WST',
  },
  {
    value: 'SHP',
    name: 'St. Helena Pound',
    label: 'St. Helena Pound (SHP £)',
    symbol: '£',
  },
  {
    value: 'SAR',
    name: 'Saudi Riyal',
    label: 'Saudi Riyal (SAR)',
    symbol: 'SAR',
  },
  {
    value: 'RSD',
    name: 'Serbian Dinar',
    label: 'Serbian Dinar (RSD)',
    symbol: 'RSD',
  },
  {
    value: 'SCR',
    name: 'Seychellois Rupee',
    label: 'Seychellois Rupee (SCR)',
    symbol: 'SCR',
  },
  {
    value: 'SLL',
    name: 'Sierra Leonean Leone',
    label: 'Sierra Leonean Leone (SLL)',
    symbol: 'SLL',
  },
  {
    value: 'SGD',
    name: 'Singapore Dollar',
    label: 'Singapore Dollar (SGD $)',
    symbol: '$',
  },
  {
    value: 'SDG',
    name: 'Sudanese Pound',
    label: 'Sudanese Pound (SDG)',
    symbol: 'SDG',
  },
  {
    value: 'SOS',
    name: 'Somali Shilling',
    label: 'Somali Shilling (SOS)',
    symbol: 'SOS',
  },
  {
    value: 'SYP',
    name: 'Syrian Pound',
    label: 'Syrian Pound (SYP £)',
    symbol: '£',
  },
  {
    value: 'ZAR',
    name: 'South African Rand',
    label: 'South African Rand (ZAR R)',
    symbol: 'R',
  },
  {
    value: 'KRW',
    name: 'South Korean Won',
    label: 'South Korean Won (KRW ₩)',
    symbol: '₩',
  },
  {
    value: 'SSP',
    name: 'South Sudanese Pound',
    label: 'South Sudanese Pound (SSP £)',
    symbol: '£',
  },
  {
    value: 'SBD',
    name: 'Solomon Islands Dollar',
    label: 'Solomon Islands Dollar (SBD $)',
    symbol: '$',
  },
  {
    value: 'LKR',
    name: 'Sri Lankan Rupee',
    label: 'Sri Lankan Rupee (LKR Rs)',
    symbol: 'Rs',
  },
  {
    value: 'SRD',
    name: 'Surinamese Dollar',
    label: 'Surinamese Dollar (SRD $)',
    symbol: '$',
  },
  {
    value: 'SZL',
    name: 'Swazi Lilangeni',
    label: 'Swazi Lilangeni (SZL)',
    symbol: 'SZL',
  },
  {
    value: 'SEK',
    name: 'Swedish Krona',
    label: 'Swedish Krona (SEK kr)',
    symbol: 'kr',
  },
  {
    value: 'CHF',
    name: 'Swiss Franc',
    label: 'Swiss Franc (CHF)',
    symbol: 'CHF',
  },
  {
    value: 'TWD',
    name: 'New Taiwan Dollar',
    label: 'New Taiwan Dollar (TWD $)',
    symbol: '$',
  },
  {
    value: 'THB',
    name: 'Thai Baht',
    label: 'Thai Baht (THB ฿)',
    symbol: '฿',
  },
  {
    value: 'TJS',
    name: 'Tajikistani Somoni',
    label: 'Tajikistani Somoni (TJS)',
    symbol: 'TJS',
  },
  {
    value: 'TZS',
    name: 'Tanzanian Shilling',
    label: 'Tanzanian Shilling (TZS)',
    symbol: 'TZS',
  },
  {
    value: 'TOP',
    name: 'Tongan Paʻanga',
    label: 'Tongan Paʻanga (TOP T$)',
    symbol: 'T$',
  },
  {
    value: 'TTD',
    name: 'Trinidad &amp; Tobago Dollar',
    label: 'Trinidad &amp; Tobago Dollar (TTD $)',
    symbol: '$',
  },
  {
    value: 'TND',
    name: 'Tunisian Dinar',
    label: 'Tunisian Dinar (TND)',
    symbol: 'TND',
  },
  {
    value: 'TRY',
    name: 'Turkish Lira',
    label: 'Turkish Lira (TRY ₺)',
    symbol: '₺',
  },
  {
    value: 'TMT',
    name: 'Turkmenistani Manat',
    label: 'Turkmenistani Manat (TMT)',
    symbol: 'TMT',
  },
  {
    value: 'UGX',
    name: 'Ugandan Shilling',
    label: 'Ugandan Shilling (UGX)',
    symbol: 'UGX',
  },
  {
    value: 'UAH',
    name: 'Ukrainian Hryvnia',
    label: 'Ukrainian Hryvnia (UAH ₴)',
    symbol: '₴',
  },
  {
    value: 'AED',
    name: 'United Arab Emirates Dirham',
    label: 'United Arab Emirates Dirham (AED)',
    symbol: 'AED',
  },
  {
    value: 'UYU',
    name: 'Uruguayan Peso',
    label: 'Uruguayan Peso (UYU $)',
    symbol: '$',
  },
  {
    value: 'UZS',
    name: 'Uzbekistani Som',
    label: 'Uzbekistani Som (UZS)',
    symbol: 'UZS',
  },
  {
    value: 'VUV',
    name: 'Vanuatu Vatu',
    label: 'Vanuatu Vatu (VUV)',
    symbol: 'VUV',
  },
  {
    value: 'VES',
    name: 'Venezuelan Bolívar',
    label: 'Venezuelan Bolívar (VES)',
    symbol: 'VES',
  },
  {
    value: 'VND',
    name: 'Vietnamese Dong',
    label: 'Vietnamese Dong (VND ₫)',
    symbol: '₫',
  },
  {
    value: 'XOF',
    name: 'West African CFA Franc',
    label: 'West African CFA Franc (XOF F CFA)',
    symbol: 'CFA',
  },
  {
    value: 'YER',
    name: 'Yemeni Rial',
    label: 'Yemeni Rial (YER)',
    symbol: 'YER',
  },
  {
    value: 'ZMW',
    name: 'Zambian Kwacha',
    label: 'Zambian Kwacha (ZMW ZK)',
    symbol: 'ZK',
  },
  {
    value: 'BYR',
    name: 'Belarusian Ruble (2000–2016)',
    label: 'Belarusian Ruble (2000–2016) (BYR)',
    symbol: 'BYR',
  },
  {
    value: 'STD',
    name: 'São Tomé &amp; Príncipe Dobra (1977–2017)',
    label: 'São Tomé &amp; Príncipe Dobra (1977–2017) (STD)',
    symbol: 'STD',
  },
  {
    value: 'STN',
    name: 'São Tomé &amp; Príncipe Dobra',
    label: 'São Tomé &amp; Príncipe Dobra (STN Db)',
    symbol: 'Db',
  },
  {
    value: 'VEF',
    name: 'Venezuelan Bolívar (2008–2018)',
    label: 'Venezuelan Bolívar (2008–2018) (VEF)',
    symbol: 'VEF',
  },
  {
    value: 'XXX',
    name: 'Unknown Currency',
    label: 'Unknown Currency (XXX)',
    symbol: 'XXX',
  },
  {
    value: 'VED',
    name: 'VED',
    label: 'VED (VED)',
    symbol: 'VED',
  },
];

export const currencyListOptions = CURRENCIES.map((item) => ({
  label: item.label,
  value: item.value,
}));
